Api/urls.py
from django.urls import path


from . import views

app_name = 'Api'
urlpatterns = [
    path('UpdateMark/', views.UpdateMark),
    path('UpdateLessonInfo/', views.UpdateLessonInfo),
    path('UpdateSemestrMark/', views.UpdateSemestrMark),
    path('UpdateSemesterInfo/', views.UpdateSemesterInfo, name='semesterInfo')
]

DiplomJournal/urls.py
from django.contrib import admin
from django.urls import path, include
from wildewidgets import WildewidgetDispatch

import Api
import Api.urls
import Main.urls
import Main

from django.contrib.auth import views as auth_views
urlpatterns = [
    #path('admin/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('admin/login/', Main.views.adminLogin, name='adminLogin'),
    path('admin/', admin.site.urls),
    path('', include(Main.urls)),
    path('api/', include(Api.urls)),

]

Main/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from wildewidgets import WildewidgetDispatch

from . import views
from django.contrib.auth import views as auth_views

from .forms import CustomAuthForm

app_name = 'Main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm),
         name='login'),
    path('workers', views.workers, name='workers'),
    path('groups', views.groups, name='groups'),
    path("logout", LogoutView.as_view(), name="logout"),
    path("group/<int:group_num>/", views.group, name='group'),
    path("group/<int:group_num>/subjects/<int:course>/<int:yearhalf>", views.subjectsMarks, name='groupSubjects'),
    path("group/<int:group_num>/<int:subject_num>", views.MarksPage.as_view(), name='marksSubject'),
    path("group/<int:group_num>/results/<int:course>/<int:yearhalf>", views.groupResults, name='semesterMarks'),
    path("user/<int:userID>", views.user, name='user'),
    path("user/<int:userID>/pastSubjects", views.teacherPastSubjects, name='teacherPastSubjects')
]

Main/models.py
import math

from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now
from ondelta.models import OnDeltaMixin
from DiplomJournal import settings

HALFYEAR = settings.HALFYEAR


class CustomUser(AbstractUser, OnDeltaMixin):
    third_name = models.CharField(max_length=100, default='', verbose_name='Отчество', null=True)
    IT = "IT"
    TEACHER = "TE"
    STUDENT = "ST"
    ADMINISTRATION = "AD"
    ROLES_CHOICES = [
        (IT, "Программист"),
        (TEACHER, "Преподаватель"),
        (STUDENT, "Студент"),
        (ADMINISTRATION, "Администрация"),
    ]
    num = models.CharField(max_length=11, null=True, verbose_name='Телефон')
    address = models.CharField(max_length=300, null=True, verbose_name='Адрес проживания')
    birthday = models.DateField(verbose_name='Дата Рождения', null=True)
    MALE = "MA"
    FEMALE = 'FE'
    FLOORS = [(MALE, "Мужской"), (FEMALE, "Женский")]
    floor = models.CharField(max_length=2, choices=FLOORS, verbose_name='Пол', null=True, default=None)
    role = models.CharField(max_length=2, choices=ROLES_CHOICES, verbose_name='Роль', null=True, default=STUDENT)

    def ondelta_role(self, old_value, new_value):
        if new_value == 'IT' or self.username == 'IvanNurgazin':
            self.is_superuser = True
        else:
            self.is_superuser = False

    @admin.display(description='ФИО')
    def get_full_name(self):
        return f"{self.last_name} {self.first_name} {self.third_name}"

    @property
    def get_Fio(self):
        return f"{self.last_name} {self.first_name[0]}.{self.third_name[0]}"

    def __str__(self):
        return self.get_full_name()


class Subject(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=400, db_index=True, verbose_name='Название предмета')
    shortName = models.CharField(max_length=100, verbose_name='Сокращённое название предмета')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Предметы'
        verbose_name_plural = 'Предметы'


class Groups(OnDeltaMixin):
    id = models.AutoField(primary_key=True)
    speciality = models.ForeignKey('Speciality', on_delete=models.PROTECT, db_index=True, null=True,
                                   verbose_name='Специальность')
    name = models.IntegerField(db_index=True, verbose_name='Номер группы')
    limit_choices_to = Q(role='TE') | Q(role='AD')
    curator = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, null=True,
                                related_name='CustomUser_groups_curator',
                                verbose_name='Куратор', limit_choices_to=limit_choices_to)
    semester = models.ForeignKey('SemesterInfo', on_delete=models.SET_NULL, null=True,
                                 verbose_name='Текущий семестр', blank=True)
    OCHNOYE = 'OC'
    ZAOCHNOYE = 'ZA'
    OTDEL = [
        (OCHNOYE, 'Очное'),
        (ZAOCHNOYE, 'Заочное')
    ]
    otdel = models.CharField(max_length=2, verbose_name='Отделение', choices=OTDEL, null=True)
    start_year = models.DateField(default=now, verbose_name='Дата зачисления группы')

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
            for course in range(1, self.speciality.years+1):
                SemesterInfo.objects.create(
                    group=self,
                    course=course,
                    semester=1
                )
                SemesterInfo.objects.create(
                    group=self,
                    course=course,
                    semester=2
                )
            SemesterInfo.objects.create(
                group=self,
                course=self.speciality.years+1,
                semester=1
            )
            if self.speciality.months >6:
                SemesterInfo.objects.create(
                    group=self,
                    course=self.speciality.years+1,
                    semester=2
                )
            self.semester = SemesterInfo.objects.get(group=self, course=1, semester=1)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.speciality.shortName}{str(self.name)}'

    class Meta:
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'


class SemesterInfo(models.Model):
    id = models.AutoField(primary_key=True)
    group = models.ForeignKey('Groups', db_index=True, on_delete=models.CASCADE, verbose_name='Группа')
    course = models.PositiveIntegerField(verbose_name='Курс', default=1, db_index=True)
    yearhalf = models.PositiveIntegerField(default=1, verbose_name='Семестр', db_index=True, validators=[
        MaxValueValidator(2),
        MinValueValidator(1)
    ])
    weeks = models.PositiveIntegerField(verbose_name='Количество недель', default=17)
    startdate = models.DateField(verbose_name='Дата начала семестра', default=now)
    rubej = models.DateField(verbose_name='Дата рубежа', default=now)

    @property
    def current(self):
        return f'{self.course} курс, {self.yearhalf} семестр'

    def __str__(self):
        return self.current

    class Meta:
        verbose_name = 'Информация о семестрах'
        verbose_name_plural = 'Информация о семестрах'


class StudentToGroup(models.Model):
    id = models.AutoField(primary_key=True)
    group = models.ForeignKey('Groups', db_index=True, on_delete=models.CASCADE, verbose_name='Группа')
    student = models.OneToOneField('CustomUser', on_delete=models.CASCADE, verbose_name='Студент',
                                limit_choices_to={'role': 'ST'}, db_index=True)
    zachotka = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Номер зачётки', null=True)
    MAINHEALTH = 'MA'
    SPECIAL = 'SP'
    PODGOTOV = 'PO'
    HEALTH_CHOICES = [
        (MAINHEALTH, 'Основная'),
        (SPECIAL, 'Специальная'),
        (PODGOTOV, 'Подготовительная')
    ]
    health = models.CharField(max_length=2, verbose_name='Группа здоровья', choices=HEALTH_CHOICES, default=MAINHEALTH)

    def __str__(self):
        return f'Обучающийся {self.student.get_full_name()} из группы {self.group.name}'

    class Meta:
        verbose_name = 'Студенты в группах'
        verbose_name_plural = 'Студенты в группах'


class Speciality(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=8, db_index=True, verbose_name='Шифр специальности')
    name = models.CharField(max_length=70, db_index=True, verbose_name='Наименование специальности')
    shortName = models.CharField(max_length=30, verbose_name='Сокращённое наименование специальности', default='')
    years = models.PositiveIntegerField(default=3, verbose_name='Годы обучения')
    months = models.PositiveIntegerField(default=10, verbose_name='Месяцы обучения')

    @admin.display(description='Время обучения')
    def get_Time(self):
        return f'{self.years} лет, {self.months} месяцев'

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'Специальности'
        verbose_name_plural = 'Специальности'


class SubjectToTeacher(models.Model):
    id = models.AutoField(primary_key=True)
    limit_choices_to = Q(role='TE') | Q(role='AD')
    teacher = models.ForeignKey('CustomUser', on_delete=models.CASCADE, null=True, verbose_name='Преподаватель',
                                db_index=True, limit_choices_to=limit_choices_to)
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True, verbose_name='Предмет', db_index=True)
    hours = models.PositiveIntegerField(verbose_name='Часы', default=1)
    group = models.ForeignKey('Groups', on_delete=models.CASCADE, null=True, verbose_name='Группа', db_index=True)
    course = models.PositiveIntegerField(verbose_name='Курс', default=1, null=True)
    yearhalf = models.PositiveIntegerField(verbose_name='Полугодие', default=1, null=True)
    diplom = models.BooleanField(default=False, verbose_name='Оценка идёт в диплом')
    active = models.BooleanField(default=False, verbose_name='Предмет преподаётся в данный момент')

    def ondelta_diplom(self, old_value, new_value):
        diplomMarks = SemesterMarks.objects.filter(subject=self, type='DI')
        students = StudentToGroup.objects.filter(group=self.group)
        if new_value is True and len(diplomMarks) == 0:
            for student in students:
                SemesterMarks.objects.create(
                    subject=self,
                    student=student,
                    type='DI'
                )
        elif new_value is False and len(diplomMarks) != 0:
            SemesterMarks.objects.filter(
                subject=self,
                type='DI'
            ).delete()

    EXAM = 'EX'
    ZACHOT = 'ZA'
    DIFZACHOT = "DZ"
    OTHER = 'OT'
    TYPE_CHOICES = [
        (EXAM, "Экзамен"),
        (ZACHOT, 'Зачёт'),
        (DIFZACHOT, 'Диффиринцированный зачёт'),
        (OTHER, 'Иные формы контроля')
    ]
    type = models.CharField(max_length=2, verbose_name='Форма аттестации', choices=TYPE_CHOICES, default=OTHER)

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
            number = 0
            for num in range(1, math.ceil(self.hours / 2) + 1):
                Lesson.objects.create(
                    subject=self,
                    group=self.group,
                    number=num
                )
                number = num
            for num in range(2):
                Lesson.objects.create(
                    subject=self,
                    group=self.group,
                    topic='Запасное занятие',
                    number=number
                )

templates/Base.html
<!DOCTYPE html>
<html lang="ru">
{% load sass_tags %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Электронный журнал</title>
    <link rel="icon" href='{% static 'img/logo.ico' %}'>
    <script src="{% static "jquery-3.7.0.min.js" %}"></script>
    <link rel="stylesheet" href={% static "font-awesome-4.7.0/css/font-awesome.css" %}>
    <link href="{% sass_src 'main.scss' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    <menu class="box">
        <img src={% static 'img/logo.webp' %}>
        <p>{{ user.get_Fio }}<br>
            {{ user.get_role_display }}</p>
        {% if user.role != 'IT'%}
            <a href="{% url 'Main:index' %}" class="custom-btn btn"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp;Личный кабинет</a>
        {% endif %}

        {% if user.role != 'ST'%}
            <a href="{% url 'Main:groups' %}" ><i class="fa fa-address-book" aria-hidden="true"></i>&nbsp;Список групп</a>
        {% endif %}
        {% if user.role == 'IT' or user.role == 'AD' %}
            <a href="{% url 'Main:workers' %}" ><i class="fa fa-users" aria-hidden="true"></i>&nbsp;Сотрудники колледжа</a>
        {% endif %}
        {% if user.role == 'IT' %}
            <a href="/admin"><i class="fa fa-code" aria-hidden="true"></i>&nbsp;Админ.панель</a>
        {% endif %}
        <a href="{% url 'Main:logout' %}" class="logout"><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp;Выйти</a>
    </menu>
    <main class="box">
        {% block body %}

        {% endblock %}
    </main>
</body>
</html>

templates/Group.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block body %}
    <script>
    let UpdateSemesterInfo = function (called, semesterID){

            $.post({
                data: {
                    'semesterID': semesterID,
                    'startdate': $("#"+semesterID+'_startdate').val(),
                    'rubej': $("#"+semesterID+'_rubej').val(),
                    'weeks': $("#"+semesterID+'_weeks').val()},
                url: '{% url "Api:semesterInfo" %}'
            })};

    </script>
    <h2>Группа {{ group.name }}</h2>
    <h3>Информация о группе</h3>
    <p>Специальность - {{ group.speciality }} {{ group.speciality.name }}, курс - {{ group.semester.course }}</p>
    <p>Студентов в группе - {{ studentsNum }}</p>
    <p>Куратор - {{ group.curator }}</p>
    {% render_table semester %}
    {% if user.role != 'ST' %}
        <h3>Список студентов</h3>
        {% render_table students %}
    {% endif %}
{% endblock %}

templates/Login.html
<!DOCTYPE html>
{% load sass_tags %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Вход в Электронный журнал КузПК</title>
    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% sass_src 'login.scss' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    <main>
        <header>
            <h3>Кузбасский педагогический колледж</h3>
            <h2>Электронный журнал</h2>
        </header>

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username }}
                {{ form.username.errors }}
                {{ form.password }}
                {{ form.password.errors }}
            </div>
            {{ form.non_field_errors }}
            <button type="submit"><i class="fa fa-sign-in" aria-hidden="true">Войти</i></button>
        </form>
    </main>
</body>
</html>

templates/Marks.html
{% extends 'base.html' %}
{% block body %}
    <script>
        let UpdateMark = function (caller, markID, newMark){
            $.post({
                data: {'markID': markID,
                        'newMark': newMark},
                url: "/api/UpdateMark/",
        })};

        let UpdateLessonInfo = function (called, lessonID){
            var date = $("#"+lessonID+'_date').val().split('-');
            var newDate = date[2]+'.'+date[1]
            $("#Dateid"+lessonID).html(newDate);
            $.post({
                data: {
                    'lessonID': lessonID,
                    'date': $("#"+lessonID+'_date').val(),
                    'type': $("#"+lessonID+'_type').val(),
                    'topic': $("#"+lessonID+'_topic').val(),
                    'task': $("#"+lessonID+'_task').val()},
                url: "/api/UpdateLessonInfo/"
            })};

            let UpdateSemestrMark = function (caller, markID, newMark){
                $.post({
                    data: {'markID': markID,
                            'newMark': newMark},
                    url: "/api/UpdateSemestrMark/",
            })};
    </script>
    <h2>{{ subject }}</h2>
    <h3>Таблица оценок</h3>
    <div class="marksTable">
        <table>
            <thead>
                <th rowspan="3" colspan="3">Оценки</th>
                <tr>{% for lesson in lessons %}
                    <th style="width: 15px;"><a href="#id{{ lesson.id }}"><div style="height:100%;width:100%">№{{ lesson.number }}</div></a></th>
                {% endfor %}
                <th></th>
                {% if diplom %}
                    <th></th>
                {% endif %}
                </tr>
                <tr>{% for lesson in lessons %}
                                <th style="width: 15px;"><a href="#id{{ lesson.id }}"><div id="Dateid{{ lesson.id }}" style="height:100%;width:100%">{{ lesson.date|date:'d.m' }}</div></a></th>
                        {% endfor %}
                    <th rowspan="7" colspan="1">
                        C
                    </th>
                    {% if diplom %}
                        <th rowspan="7" colspan="1">
                            Д
                        </th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for student, marks in students.items %}
                        <tr>
                        <th colspan="3">{{student.get_Fio}}</th>
                        {% for mark in marks %}
                            {% if mark.type == 'Normal' %}
                                <td style="width: 15px;" colspan="1"><input style="width: 15px;" type="text"
                                                                            {% if user.id != teacher.id %} disabled{% endif %}
                                                                            name="{{ mark.id }}" value="{{ mark.mark }}" maxlength="1"
                                    oninput="UpdateMark(this, markID=this.name, newMark=this.value)"></td>
                            {% else %}
                                <td colspan="1"><input type="text" style="width: 60px;"
                                                       {% if user.id != teacher.id %} disabled {% endif %}
                                                       name="{{ mark.id }}" value="{{ mark.mark }}" maxlength="8"
                                    oninput="UpdateSemestrMark(this, markID=this.name, newMark=this.value)"></td>
                            {% endif %}
                        {% endfor %}
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
    <h3>Информация о занятии</h3>
    <table>
        <thead>
            <th style="width: 5%">№</th>
            <th style="width: 10%">Дата</th>
            <th style="width: 10%;">Тип</th>
            <th style="width: 30%;">Тема занятия</th>
            <th>Самостоятельное задание</th>
        </thead>
        <tbody>
        {% for lesson in lessons %}
            <tr id="id{{ lesson.id }}">
                <td style="width: 5%; padding: 0px">
                    {{ lesson.number }}
                </td>
                <td style="width: 10%; padding: 0px">
                    <input id="{{ lesson.id }}_date"
                           {% if user.id != teacher.id %} disabled {% endif %}
                           type="date" value="{{ lesson.date|date:'Y-m-d' }}"
                        oninput="UpdateLessonInfo(this, {{ lesson.id }})">
                </td>
                <td style="width: 10%; padding: 0px">
                    <select style="width: 100%; height: 100%"
                            {% if user.id != teacher.id %} disabled {% endif %}
                            id="{{ lesson.id }}_type"
                    oninput="UpdateLessonInfo(this, {{ lesson.id }})">
                        {% for choice in choices %}
                            {% if choice|first == lesson.type %}
                                <option selected="True" value="{{ choice|first }}">{{ choice|last }}</option>
                            {% else %}
                                <option value="{{ choice|first }}">{{ choice|last }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </td>
                <td style="width: 30%; padding: 0px;">
                    <textarea maxlength="125"
                              {% if user.id != teacher.id %} disabled {% endif %}
                        id="{{ lesson.id }}_topic"
                        oninput="UpdateLessonInfo(this, {{ lesson.id }})">{{ lesson.topic }}</textarea>
                </td>
                <td style="padding: 0px;">
                    <textarea style="resize: none; overflow: auto" maxlength="500"
                              {% if user.id != teacher.id %} disabled {% endif %}
                        id="{{ lesson.id }}_task"
                        oninput="UpdateLessonInfo(this, {{ lesson.id }})">{{ lesson.independentTask }}</textarea>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/Semester.html
{% extends 'base.html' %}
{% block body %}
    <h3>Сводная ведомость за {{ course }} курс, {{ yearhalf }} полугодие</h3>
    <div class="marksTable">
        <table>
            <thead>
                <tr>
                    <th rowspan="3" colspan="3">Сводная ведомость</th>
                    <th colspan="{{ semesters }}">
                        Семестр
                    </th>
                    {% if diploms != 0 %}
                        <th colspan="{{ diploms }}">
                            Диплом
                        </th>
                    {% endif %}
                </tr>
                <tr>{% for name in semesterNames %}
                    <th style="writing-mode:tb-rl; vertical-align: middle;"><div style="height:100%;width:100%;">{{name}}</div></th>
                {% endfor %}
                {% for name in diplomNames %}
                    <th><div style="writing-mode:tb-rl; width: max-content;width:100%">{{name}}</div></th>
                {% endfor %}
            </thead>
            <tbody>
                <tr>
                    {% for student, semester, diplom in students %}
                        <tr>
                        <th colspan="3">{{student}}</th>
                        {% for mark in semester %}
                                <td style="width: 15px;" colspan="1">{{ mark.mark }}</td>
                        {% endfor %}
                        {% for mark in diplom %}
                                <td style="width: 15px;" colspan="1">{{ mark.mark }}</td>
                        {% endfor %}
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
    </table>
    </div>
{% endblock %}

templates/TablePage.html
{% extends 'base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% block body %}
    <h2>{{ title }}</h2>
    {% render_table table %}
{% endblock %}

templates/User.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block body %}
    <h2>Личная информация пользователя</h2>
    <p>ФИО - {{ full_name }}</p>
    <p>Роль - {{ userFind.get_role_display }}</p>
    <p>Дата рождения - {{ userFind.birthday }}</p>
    <p>Номер телефона - {{ userFind.num }}</p>
    <p>Проживает по адресу - {{ userFind.address }}</p>
    {% if userFind.role == 'ST' %}
        {% if exist %}
            <p>Обучается в группе - <a href="{% url 'Main:group' group_num=group.name%}"><span title="{{ group.speciality.code }} {{ group.speciality.name }}">{{ group.name }}</span></a></p>
            <h3>Актуальные предметы: </h3>
            {% render_table subjects %}
        {% else %}
            <h3>Пока студент не привязан к группе!</h3>
        {% endif %}
    {% endif %}
    {% if curator %}
        <p>Является Куратором следующих групп:
        {% for group in curator %}
            <a href="{% url "Main:group" group_num=group.name %}"> {{ group }} </a>
        {% endfor %}</p>
    {% endif %}
    {% if userFind.role == 'AD' or userFind.role == 'TE'%}
        <p><a href="{{ userFind.id }}/pastSubjects">Предметы, которые ранее преподавал преподаватель</a></p>
        <h3>Преподаёт следующие предметы: </h3>
        {% render_table subjects %}
    {% endif %}
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block body %}
    <div class="day">
        Понедельник
        <input type="color">
    </div>
    <script>
    var finduser = function (caller, mark){
            var textarea = caller
            $.post({
                data: {'userID': 1,
                    'mark': mark},
                url: "/api/test/",
        })};
    </script>
{% endblock %}